### ISSUE TITLE
ATR index error

### ISSUE THREAD

**Issue by selimozbas** [TulipCharts/tulipindicators#106]
Hi,

when I try to get atr with this command

data = client.get_klines(symbol=pair, interval=period)

        high = [float(entry[2]) for entry in data]
        low = [float(entry[3]) for entry in data]
        close = [float(entry[4]) for entry in data]
        
        close_array = np.asarray(close)
        high_array = np.asarray(high)
        low_array = np.asarray(low)

for i in range(0, len(close_array)):
     atrc = get_atr[i]

I receive following error 
IndexError: index 408 is out of bounds for axis 0 with size 408

**Comment by codeplea** [comment]
This is the C code repo.

**Comment by meysamiran** [comment]
for i in range(0, len(close_array)-1):
