### ISSUE TITLE
Add VWAP?

### ISSUE THREAD

**Issue by saulfautley** [TulipCharts/tulipindicators#11]
Would it be possible to add a VWAP indicator?

https://www.investopedia.com/terms/v/vwap.asp

Thanks for the great work on this library btw. Tulip is by far the best one I've tried.

**Comment by codeplea** [comment]
Isn't this VWAP essentially the same as VWMA: (https://tulipindicators.org/vwma), which is already implemented?

**Comment by codeplea** [comment]
Sorry, I think they are actually quite different. I will look into adding VWAP. New issue at: https://github.com/TulipCharts/tulipindicators/issues/32
