### ISSUE TITLE
Docs Duplicate Indicator to %R: Quality Factor (%Q)

### ISSUE THREAD

**Issue by kevindirect** [TulipCharts/tulipindicators#118]
First off thanks for this great library.

This is something I noticed when looking for the Quality Factor (%Q) indicator ([Ref](https://deepai.org/publication/financial-time-series-data-processing-for-machine-learning), page 5) and looking at the docs on Williams %R.

%Q is %R without the -100 multiplier. Maybe something to add to the docs. I would have submitted a PR but didn't know how for this.

**Comment by codeplea** [comment]
Which indicator are you even talking about?

**Comment by kevindirect** [comment]
I was talking about the Quality Factor indicator. Here is the reference again: https://deepai.org/publication/financial-time-series-data-processing-for-machine-learning

Wilders %R = -100 * Quality Factor (%Q)

I think it's something to add to the docs because other duplicates / affine transforms of indicators are documented for other indicators.

**Comment by codeplea** [comment]
I don't know what you're talking about. What does this have to do with Tulip Indicators? What docs are you saying I should update? Where are you saying other duplicates are documented?

**Comment by kevindirect** [comment]
I was talking about this documentation: https://tulipindicators.org/willr
It doesn't matter anyways; I was mistaken about something.
