### ISSUE TITLE
Divide by Zero in ADX, ADXR, DI, and DX

### ISSUE THREAD

**Issue by codeplea** [TulipCharts/tulipindicators#12]
See https://github.com/TulipCharts/tulipnode/pull/34

These formulas divide by ATR, which could be zero. Currently a divide-by-zero results in returning NaN. We should consider if this is appropriate or not.

**Comment by ankasem** [comment]
hi
npm install tulip

Why does not work

**Comment by LooOOooM** [comment]
any news on that issue?

**Comment by codeplea** [comment]
Before it's "fixed", there should be a discussion if it's broken or not. Tulip Indicators currently follows the formula given by Wilder, J. Welles in (1978) New Concepts in Technical Trading Systems. Wilder's formulas will divide by zero. If we're to deviate from that standard, it needs to be well thought out.

I think that if ATR becomes zero, then DI (and by extension DX, ADX, ADXR) don't make sense. Returning NaN in this circumstance communicates that very clearly.

My questions would be:
1) Why is having NaN not desirable?
2) What do other TA libraries do?
3) What do other charting programs do?
4) What would a "fix" look like?

If a "fix" is detecting the condition and returning 0 instead of NaN, that seems dangerous and disingenuous (because 0 is a valid return value, you're essentially hiding the error from the caller).

So the delay isn't because "nobody is caring", as you stated in the other thread, but actually because I care a lot. I don't want to get it wrong.

**Comment by LooOOooM** [comment]
Please read this https://www.macroption.com/atr-excel-wilder/ as there are more then one way of smoothing the TR.

In addition we need to keep in mind what we want actually to messure with ADX,- > the strangth of a trend. Logicly, if the ATR stays zero for a specific periot means that there is simply no trend .... No trend = ADX = 0

**Comment by codeplea** [comment]
https://tulipindicators.org/dx

Actually, when ATR approaches 0, then +DI and -DI approach infinity. Because +DI and -DI are in both the numerator and denominator, you are right that ADX would approach 0.

So I just realized that ATR does actually cancel out in the calculation of DX, ADX, and ADXR. I'm a bit embarrassed that I didn't notice this earlier. In my defense, Welles Wilder uses ATR in the calculations back in the 70s, when he was presumably doing it all by hand. Perhaps he only did it that way because he was interested in +DI and -DI directly.

So I've removed ATR from DX, ADX, and ADXR. The code passes all the tests and returns the same values as before (assuming ATR > 0). It also runs faster. I put the changes in this branch: https://github.com/TulipCharts/tulipindicators/tree/adx_nan

A side-effect of this is that the close price is no longer used in the calculation of DX, ADX, and ADXR. If I change the interface, this would make it a breaking update, so I want to be careful about how I handle that. For now, I may just push the changes to master while keeping the interface the same.

I will probably change the interface for version 0.9.

**Comment by allanster** [comment]
RE: "altering DX, ADX, and ADXR calculations to no longer use close".

If I am understanding correctly you are considering altering the pure and original formula only so that devs do not have to handle NaN in their own code?

In my humble opinion this should not be done. It should adhere to Wilder's original formula and devs should adapt their code to gracefully handle this.

**Comment by allanster** [comment]
RE: "2. What do other TA libraries do?"

The TA library ta4j uses NaN extensively... https://github.com/ta4j/ta4j/search?q=NaN&unscoped_q=NaN

The ta4j library uses Wilder's formula as well and references that in their code pictured below... https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/adx/PlusDIIndicator.java

![screen shot 2018-11-27 at 12 54 33 pm](https://user-images.githubusercontent.com/32180061/49104458-a8970400-f243-11e8-84d6-25af885d6d4b.png)

**Comment by codeplea** [comment]
@allanster Thanks for your feedback! The code samples are quite illustrative.

>If I am understanding correctly you are considering altering the pure and original formula only so that devs do not have to handle NaN in their own code?

No. What I am saying is that if you look at the formula for DX (and by extension ADX, ADXR), you will see that ATR doesn't do anything. ATR appears in both the numerator and denominator. You can cancel it out algebraically. I already modified the code (in the `adx_nan` branch), and you can test that it calculates the same results as before.

I'll have to look deeper into DX to see if there are other situations when it could return NaN.

I think that DI will have to keep returning NaN when ATR is 0. I really don't see any work-around there.

>TradingView's indicators allow for NaN. This is their code pictured below.

![49102926-b0ed4000-f23f-11e8-985c-0c4b4bd2a51d](https://user-images.githubusercontent.com/14815717/49108929-03822880-f24f-11e8-9695-63e643fdb999.png)

Looks like `plus` or `minus` could be NaN. However, the part I circled is clearly to prevent another possible NaN. It *is* a deviation from Wilder's formula. So is TradingView doing the right thing here? I think that if `sum` is zero, then the numerator will also be zero, so it may be justified to set ADX = 0 as TradingView does.

**Comment by allanster** [comment]
@codeplea thanks for your response and explanation. I suspected I was likely misinterpreting.

**Comment by LooOOooM** [comment]
Big thx for the clarification and your care !!!

**Comment by codeplea** [comment]
Provided that no one objects, my plan is to resolve this in the 0.9 release.

1) I will remove the close price input (and therefor ATR) from DX, ADX, and ADXR, as it seems irrelevant - despite every other indicator/charting packing reading it in. Because `close` is passed in last, this actually shouldn't break anybody's code.

2) I will set ADX = 0 where `+DI` = 0 and `-DI` = 0. This is what TradingView and other charting programs do, and it still keeps the output continuous.

3) There may still be situations where ADX returns NaN, I'm not sure. If so, it will continue to return NaN in those situations.

4) DI will still return NaN when ATR = 0.

5) I will do a ton of testing to make sure my assumptions are correct and we're not actually changing the output value.

If anyone sees any issue with this, please let me know.

**Comment by codeplea** [comment]
These changes are merged into 0.9 now. DX, ADX, and ADXR no longer take `close` as an input. They still calculate the same result and pass the same tests.

This shouldn't break anyone's code, as close is the last input. If it's passed in, it will be ignored.
