### ISSUE TITLE
RSI smoothing algorithm

### ISSUE THREAD

**Issue by Doweig** [TulipCharts/tulipindicators#15]
Hello there,

First of all I wanna say this library is amazing, thank you so much for your work.
I have a question about the RSI, the doc doesn't say with smoothing algorithm you use to calculate it, something like sma or ema?
Reading the code it looks like sma, want to double check.
https://github.com/TulipCharts/tulipindicators/blob/master/indicators/rsi.c#L63

Thank you in advance.

**Comment by codeplea** [comment]
Thanks for the kind words. I'm glad you're finding the library useful.

RSI is implemented as described by Welles Wilder in [New Concepts in Technical Trading Systems (1978)](http://www.amazon.com/exec/obidos/ASIN/0894590278/tulind-20) page 63. You can see the math at [https://tulipindicators.org/rsi](https://tulipindicators.org/rsi). It employs [Wilders Smoothing](https://tulipindicators.org/wilders), which is equivalent to exponential smoothing.

**Comment by ankasem** [comment]
hi
npm install tulip

Why does not work
rsi-adx 
I can not use

**Comment by Doweig** [comment]
Thank you for the clarification.
