### ISSUE TITLE
A BIG THANK YOU!!!!!

### ISSUE THREAD

**Issue by Think7** [TulipCharts/tulipindicators#17]
Greetings, 

I just wanted to take a moment and say THANK YOU for releasing this library.

I cannot express how happy i am to have found it. 

It's small, self contained, extremely well designed, and performant beyond anything else i've found.

Integrating it into my project has been a breeze and in general you've taken a task i've been dreading and made it exciting.

I've created an issue at https://fffaraz.github.io/awesome-cpp/ to recommend this fantastic resource. (Hope that's ok.)

Please accept this friendship pienaple: 🍍

**Comment by codeplea** [comment]
Hi Andrew. Thanks for the kind words. I'm glad you're enjoying the library.

Thanks for suggesting it for the awesome-cpp list. The more publicity the better!

**Comment by codeplea** [comment]
It's been added to the list at https://fffaraz.github.io/awesome-cpp/

Hopefully this will help bring in even more interest in the project.
