### ISSUE TITLE
Makefile doesn't work on Windows (with fix)

### ISSUE THREAD

**Issue by Yoonwoo** [TulipCharts/tulipindicators#18]
The makefile on Windows has an error because of the first line:

CC ?= gcc

It then runs the command cc instead of gcc.

I had to change it to CC = gcc.

**Comment by Yoonwoo** [comment]
Oh no, theres no problem at all. I just put the issue here in case someone using Windows has the same thing happen. It seems this only happened to me though so idk.

My version of MinGW is:
GNU Make 4.2.1
Built for x86_64-w64-mingw32

**Comment by codeplea** [comment]
I think MinGW is supposed to either copy `gcc` to `cc` or create a link. See here: https://sourceforge.net/p/mingw/bugs/1552/

You might want to  "ln -s ./gcc.exe ./cc.exe".

However, I do want my Makefile to work on a fresh MinGW install, so I'm going to keep looking into this.

**Comment by Yoonwoo** [comment]
I agree. And while not a clean solution, maybe just stick a footnote in the readme for troubleshooting. But maybe this issue is too rare and minor for that.
