### ISSUE TITLE
don't understand how to use the macd function

### ISSUE THREAD

**Issue by Tasheehoo** [TulipCharts/tulipindicators#24]
Hi,

I'm trying to use the ti_macd() function.
The initial parameters are: 12, 26, 9
I call the ti_macd_start() function as follows:
```cpp
const double options[] = {
     (double)(fast_period)
    ,(double)(slow_period)
    ,(double)(signal_period)
};
std::size_t produced = ti_macd_start(options);
```
Now the `produced` var is equal `25`.
I have the `std::vector<double>` with size `26`.
Next, I allocate the `std::vector<double>`s for outputs and call the `ti_macd()` as follows:
```cpp
std::vector<double> inarr = {...}; // 26 doubles with closed vals
const double *inputs[] = {&inarr[0]};

std::vector<double> macd_fast(produced);
std::vector<double> macd_slow(produced);
std::vector<double> macd_hist(produced);
double *outputs[] = {
     &macd_fast[0]
    ,&macd_slow[0]
    ,&macd_hist[0]
};
int ec = ti_macd(slow_period, inputs, options, outputs);
assert(!ec);
```
After that in the `macd_fast` and `macd_slow` vectors only first element is not null. However the `macd_hist` vector contains only zeros.

Ideas?

**Comment by codeplea** [comment]
The start function `ti_macd_start` tells you how much shorter your output will be than your input. So if `ti_macd_start` returns 25, and you pass in 100 bars of input, the output will be 75 bars long. Likewise, if you pass in 26 bars as input, the output would only be 1 bar. You should either pass in many more input bars, or you should use different options.

**Comment by Tasheehoo** [comment]
Aah, that's it =)
Sorry for the noise.

Then my question is, why the `macd_hist` vector contains only zeros?

**Comment by Tasheehoo** [comment]
If you say "function ti_macd_start tells you how much shorter your output will be than your input" - then how I should use the `ti_aroon_start()` function? Its always returns the same value that it takes!: https://github.com/TulipCharts/tulipindicators/blob/master/indicators/aroon.c#L29

**Comment by Tasheehoo** [comment]
ping, please?

**Comment by codeplea** [comment]
`macd_hist` is the difference of `macd_fast` and `macd_slow`. So if you look at `macd_fast` and `macd_slow` I think you will find that they are the same value, and therefore `macd_hist` should be 0.

Do you know how aroon works? See https://tulipindicators.org/aroon Work it out by hand, and you will see that if you use a period of N, then your output will be N bars shorter than your input. So of course `ti_aroon_start()` returns the period you pass to it.

**Comment by Tasheehoo** [comment]
> So if you look at macd_fast and macd_slow I think you will find that they are the same value
You right!

> Do you know how aroon works?
I am very new to this area...
I just read the description of the aroon.

Sorry, but in the previous comment I wrote nonsense...

Closed.

**Comment by codeplea** [comment]
>I am very new to this area...

Everyone has to start somewhere. I'm glad you're on the right track now.

**Comment by Tasheehoo** [comment]
Hi again.

I do not fully understand the MACD algorithm, so I will try to explain my problem, because I get a strange result.

I accept kline messages from the exchange in real time. I add each new kline to the end of the list (std::list<>). In fact, I need to calculate the MACD only for the last kline in order to display it on the chart. But I do not understand how much klines I should pass to the MACD function in order to get the correct value of the last kline.

My question is how much klines should I pass to the MACD function to calculate the last kline and what does it depend on?

**Comment by codeplea** [comment]
MACD is based on the math for exponential moving average. So you should study EMA. Basically, if your period is X, then you need to pass in several times X worth of data for the indicator to reach an equilibrium. In your case, I would pass in the last 250 bars of data.

If you look at the math for EMA (https://tulipindicators.org/ema) you will see that actually every bar effects the indicator. Even a price movement 10 years ago will affect the current EMA value in a tiny way. If you pass in at least 250 bars, it should smooth out enough that the difference before that is negligible. BTW, Tulip Indicators can process 300 million bars for MACD in a second, so don't worry about 250 bars slowing it down.

**Comment by Tasheehoo** [comment]
Thanks for your answers!

I was received the strange values due to an error in my code.

250 bars really was enough to obtain the correct relative values.

Regarding the speed of calculating MACD - I am writing a trading bot and I need to calc MACD+AROON+MA after receiving information about each closed order, the exchange sends this messages using websockets, and these messages can arrive at speeds of up to 30 per second (I saw this).

For now, I’ll close this ticket and hope that I don’t have to bother you again =)

Thank you!
