### ISSUE TITLE
Incorrect adx values

### ISSUE THREAD

**Issue by moo5e** [TulipCharts/tulipindicators#29]
Hello,
The values im getting from the adx function at a 14 timeperiod are correct but when I try to run it at a 25 timperiod, the results I get are off by a little bit. Is this is an error within my system or from the tulip libray? It seems that any value other than 14 returns an incorrect result.

**Comment by codeplea** [comment]
Tulip Indicators is very carefully tested. It's unlikely to be a bug with TI.

Make sure you're passing in enough input bars. If you still can't figure it out, post your input, output, and what you expected the output to be. Without that, nobody can really help you.

**Comment by codeplea** [comment]
ADX is based on an exponential moving average. Even an input from a very long time ago will affect the current output. So you should pass in a lot of input bars.

**Comment by moo5e** [comment]
Cannot get it to work right so im using the 14 time period for now.
