### ISSUE TITLE
0.9 Roadmap

### ISSUE THREAD

**Issue by codeplea** [TulipCharts/tulipindicators#35]
I will be updating this post as progress is made.

If you have comments on individual indicators, please post in their respective issue (open an issue if needed).

**New features:**
Reference indicators - https://github.com/TulipCharts/tulipindicators/issues/59
Streaming interface - https://github.com/TulipCharts/tulipindicators/issues/57
Candlestick pattern recognition - this is done, but hasn't been publicly released yet
Indicators can be marked as beta. This will get new indicators out faster.

**New indicators:**
Arnaud Legoux moving Average (by @johanhenriksson)
Acceleration Bands - https://github.com/TulipCharts/tulipindicators/pull/47
Chaikin Money Flow - https://github.com/TulipCharts/tulipindicators/issues/16
Chandelier Exit - https://github.com/TulipCharts/tulipindicators/pull/58
Choppock Curve
Crossdir - https://github.com/TulipCharts/tulipindicators/pull/110
Donchian Channel - https://github.com/TulipCharts/tulipindicators/issues/13
Force Index - https://github.com/TulipCharts/tulipindicators/issues/31
Ichimoku (several indicators) by (@yageek) - https://github.com/TulipCharts/tulipindicators/issues/36
Know Sure Thing - https://github.com/TulipCharts/tulipindicators/issues/30
Keltner Channels - https://github.com/TulipCharts/tulipindicators/issues/22
MESA Adaptive Moving Average
Polarized Fractal Efficiency
Price and Volume Trend
Price Channel
Projection Bands
Projection Oscillator
Relative Momentum Index
Relative Volatility Index
Schaff Trend Cycle - https://github.com/TulipCharts/tulipindicators/issues/5
Stochastic Momentum Index
True Strength Indicator - https://github.com/TulipCharts/tulipindicators/issues/2
Volume Weighted Average Price - https://github.com/TulipCharts/tulipindicators/issues/32

**New Indicators that are close variations of old ones:**
Parabolic SAR - https://github.com/TulipCharts/tulipindicators/issues/19
StochRSI - https://github.com/TulipCharts/tulipindicators/issues/23

**Changes:**
✓ DX, ADX, ADXR no longer take `close` as in input. - https://github.com/TulipCharts/tulipindicators/issues/12
✓ DX, ADX, ADXR avoid *unnecessary* NaNs - https://github.com/TulipCharts/tulipindicators/issues/12
✓ Fix outputs names for ADX and ADXR (previously was 'dx', now is 'adx' and 'adxr' respectively)
Better testing in `benchmark` - https://github.com/TulipCharts/tulipindicators/issues/20
Make untest.txt use more data. Ensure it gets results for indicators with long periods, such as AO.

**Contributing:**
Any help is appreciated, please read https://github.com/TulipCharts/tulipindicators/blob/master/CONTRIBUTING

Sponsorship will greatly accelerate the timeline. If anyone is interested, please get in touch.

**Comment by yageek** [comment]
By working on the Ichimoku's family indicator, I'm facing some questions about the API.

I'm using wikipedia as the reliable source of informations.

According to [Ichimoku Kinko H](https://fr.wikipedia.org/wiki/Ichimoku_Kinko_Hyo),
the family of indicators contains 6 members:

- **Tenkan-Sen**:
     Average of highest and lowest prices over a `T_ts` period.
     Standart value: `T_ts = 9`.
- **Kijun-Sen**:
    Average of highest and lowest prices over a `T_ks` period. Same method as *Tenkan-Sen*.
    Standart value: `T_ks = 26`.
- **Chikou Span**:
    Backward projection of close prices over a `T_cs` period.
    Standart value: `T_cs = 26`.
- **Senkou Span A**:
    Forward projection over a `T_ssa` period of the average of *Tenkan-Sen* and *Kijun-Sen*.
    Standart values: `T_ssa=52`, `T_ts = 9` and `T_ks = 26`.
- **Senkou Span B**:
    Forward projection over a `T_ssb_proj` period  of the average over a period of `T_ssb_avg` of the highest and lowest price.
    Standart values: `T_ssb_proj=52` and `T_ssb_avg = 26`.

According to different sources( https://www.investopedia.com/terms/i/ichimoku-cloud.asp - http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:ichimoku_cloud - https://www.daytrading.com/ichimoku-cloud) computing any ichimoku indicators **implies** using the standart values. This remark and the inter-dependencies of indicators lead
me to some questions:

- Do we offer the possibility to the user to customize the different period values (`T_ts`, `T_ks`, `T_cs`, `T_ssa`, `T_ssb_proj`, `T_ssb_proj` and `T_ssb_svg`)?

I was thinking to offer the possibility to the user. In case he passes a `NULL` `option` parameters, the standart values are used.

- Do we create one function by indicator or should we create one uniq indicators that outputs all the values at once?

I would propose to create one function per indicator. In the case of **Tenkan-Sen** and **Kijun-Sen**, we may use one private function with two public aliases, as the computation
process is the same.

Any feedback on this?

**Comment by Malacarne** [comment]
@codeplea , have you ever thought about converting the library do C++, and use vectors, instead of using C-style arrays?

**Comment by codeplea** [comment]
This issue is purely for the 0.9 release progress. If you have questions, please open a new issue.
