### ISSUE TITLE
KVO indicator has wildly different value output then KVO indicator on Tradingview

### ISSUE THREAD

**Issue by vgroenewold** [TulipCharts/tulipindicators#37]
I'm using the KVO indicator from HPotter on Tradingview. Set it to Fast 34 and Slow 55, I did the same in my script using the Tulip KVO library; optInFastPeriod = 34 and the slow period = 55. I look at 4h candles in both cases and on Tradingview at some point it reports almost 0, but the Tulip indicator is at 20.000. The script did make some good decisions but I'm wondering which one I should trust now. :)

**Comment by codeplea** [comment]
All of Tulip Indicators is carefully checked. The formula used for KVO is given here: https://tulipindicators.org/kvo

KVO can return some truly huge values. Depending on how you're passing in inputs, 20 and 0 may actually be a very small difference.

It's probably not possible to help you further without seeing your code, inputs, and outputs. I also highly recommend you pop your data in Excel and calculate it by hand, and try to understand what's actually happening.

**Comment by vgroenewold** [comment]
That's a great suggestion indeed, I will do that thank you. It can vary wildly yes, I was just wondering as the difference is so big between the two, on Tradigview the graph shows values hovering around 10K to -10K with that 10K being a big jump in price as well. So that seems to be the range there, give or take. If that graph shows a period of values at around -5K all the time and the tulip indicator is at 10K that seems odd to me. There must be a difference between the 2 somehow. My code for the tulip indicator is used in the Gekko bot which simply gets the Tulip indicator by adding it to the strategy and I can then access the result value, it seems to make sense while testing, the only thing is the huge difference between the graphs that supposedly use the same calculations.

But I'll carefully look at the code on trandigview first and compare.

**Comment by codeplea** [comment]
Were you able to figure out anything else on this?

**Comment by vgroenewold** [comment]
Unfortunately not, I decided to use another indicator. It might have something to do with when I was checking the market versus the candle-times on tradingview.
