### ISSUE TITLE
Swift bindings

### ISSUE THREAD

**Issue by joshhopkins** [TulipCharts/tulipindicators#39]
Swift is now a very viable contender in FinTech. Be great to have support here.

**Comment by codeplea** [comment]
Are you offering to help?

**Comment by yageek** [comment]
Fixed here: https://github.com/yageek/tulipindicators-swift

**Comment by joshhopkins** [comment]
This is great. Nice work @yageek!

**Comment by codeplea** [comment]
Thanks @yageek!
