### ISSUE TITLE
Add StochRSI

### ISSUE THREAD

**Issue by Patafix** [TulipCharts/tulipindicators#4]
Hello,

Can you add StockRSI indicator : 
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:stochrsi

Or maybe i can use stoch and rsi to get it ?

thank you for this awesome library

**Comment by codeplea** [comment]
I have a list of indicators that I'm planning on adding for the next release. I'll look at adding StockRSI at that time (may be a couple of months).

**Comment by mithunweinvest** [comment]
any update on this? or can you at least share how to calculate this using Stoch and RSI?

**Comment by mithun35h** [comment]
Can you please share how to calculate StochRSI using Stoch and RSI??

Thanks

**Comment by keithfawcett** [comment]
@codeplea Any updates on adding Stochastic RSI (a.k.a Stoch RSI)?

**Comment by codeplea** [comment]
stochrsi has been added to Tulip Indicators.

Special thanks to [Gunthy](https://gunthy.org) who sponsored the work!

If anyone else is interested in sponsoring work on Tulip Indicators, please get in touch.
