### ISSUE TITLE
ATR values look odd.

### ISSUE THREAD

**Issue by LooOOooM** [TulipCharts/tulipindicators#43]
The result of your ATR calculation and result on trading view looks different.

In addition I noticed the following: 
Pease take a look at the this tables: https://www.macroption.com/atr-excel/
In those examples your can find that for an propper ATR i.e. ATR 5 you need 6 rows of input data.
- One as a starting point
- 5 for the the needed 5 TRs
- to get 1 ATR

conclusion: ATR5 needs 5+1 Rows of inputdata.
On the linked URL it says also: 

> Because the inputs include previous close, we can’t calculate true range for the first row of our data, so we will start with the second

However your lib needs for an ATR5 just 5 rows and I wounder how you get the first TR value or if all ATR output is just TR output rather then realy ATR output.

```
var tulind = require('tulind');
var indicator = "atr"
var high  = [9,7,8,7,8,8,7,7,8,7];
var low   = [1,2,3,3,2,1,2,2,2,3];
var close = [4,5,6,6,6,5,5,20,6,4];
console.log(tulind.indicators[indicator]);
tulind.indicators[indicator].indicator([high, low, close], [10], function(err, results) {
  console.log("Result of "+indicator+" is:");
  console.log(results);
});

```
results in:

```
{ name: 'atr',
  full_name: 'Average True Range',
  type: 'indicator',
  inputs: 3,
  options: 1,
  outputs: 1,
  input_names: [ 'high', 'low', 'close' ],
  option_names: [ 'period' ],
  output_names: [ 'atr' ],
  indicator: [Function],
  start: [Function] }
Result of atr is:
[ [ 6.7 ] ]
```

However it should result in [[]] as the minimum rows for inputdate for an ATR10 is 11.

**Comment by codeplea** [comment]
Your link is using a simple moving average for ATR smoothing. Tulip Indicators uses Wilder's smoothing, which is documentation here: https://tulipindicators.org/atr Wilder's smoothing is the proper way to do ATR, as that's the method used by Wilder (the author of ATR).

**Comment by LooOOooM** [comment]
If I take a look at the formular, I can see that the ATR is based on the ATR and the closes of the day before. It is still not clear to me how you get the realy first ATR5 and closes if there are just 5 rows of OHLC data.

**Comment by codeplea** [comment]
The True Range for the first day is `high - low`, as described by the author of ATR, Welles Wilder, "New Concepts in Technical Trading Systems" page 23.

An additional reference is "Technical Analysis A to Z" by Steven Achelis, page 68, which shows the same.

Both of these books are listed at https://tulipindicators.org/atr

You know that Tulip Indicators is open source, right? https://github.com/TulipCharts/tulipindicators/blob/master/indicators/atr.c
