### ISSUE TITLE
TI_INDICATOR_COUNT and concurrent PRs

### ISSUE THREAD

**Issue by rdbuf** [TulipCharts/tulipindicators#45]
In case of merging several concurrent PRs, the value of the macro will get invalidated.

**Comment by rdbuf** [comment]
If it's a feature that we don't depend on anything but a C compiler, we could easily generate those for releases only.

**Comment by codeplea** [comment]
After merging, I'll need to run `indicators.tcl`.

You were asking before about `indicators.h` and `indicators_list.c`. I'm open to omitting them, but the CI (.travis.yml) would need to be updated.

**Comment by rdbuf** [comment]
OK.

So, if all that's needed is a CI reconfiguration, I will make a PR.

**Comment by codeplea** [comment]
I think this is resolved in 0.9.
