### ISSUE TITLE
Testing infrastructure

### ISSUE THREAD

**Issue by rdbuf** [TulipCharts/tulipindicators#48]
Is it necessary to have `smoke.c` and `utils/minctest.h` with a handrolled parser and a load of macros and three separate test suites (`tests/atoz.txt`, `tests/extra.txt`, `tests/untest.txt`)?

Wouldn't it be simpler to have a single set of testcases and generate simple test programs from their description, like so:

```
lappend testcases [list "vwma" {4} {
    {50.25,50.55,52.5,54.5,54.1,54.12,55.5,50.2,50.45,50.24}
    {12412,12458,15874,12354,12456,12542,15421,19510,12521,12041}
} {
    {51.9819,52.8828,53.7204,54.6075,53.1948,52.4340,51.6345}
}]
```

which turns into

```
#include <stdio.h>
#include <math.h>
#include <stdbool.h>

#include "../indicators.h"

int main() {
    const ti_indicator_info *info = ti_find_indicator("vwma");
    TI_REAL const input_0[] = {50.25,50.55,52.5,54.5,54.1,54.12,55.5,50.2,50.45,50.24};
    TI_REAL const input_1[] = {12412,12458,15874,12354,12456,12542,15421,19510,12521,12041};
    const TI_REAL* inputs[] = {
        input_0, input_1, 
    };
    const TI_REAL option_0 = 4;
    const TI_REAL options[] = {
        option_0, 
    };
    const int size = 10;
    const int out_size = size - ti_vwma_start(options);
    TI_REAL *output_0 = malloc(out_size * sizeof(TI_REAL));
    TI_REAL *outputs[] = {
        output_0, 
    };
    TI_REAL expected_output_0[] = {51.9819,52.8828,53.7204,54.6075,53.1948,52.4340,51.6345};
    printf("running testcase vwma...\n");
    ti_vwma(size, inputs, options, outputs);
    bool ok, any_failed = false;

    ok = true;
    for (int i = 0; i < out_size; ++i) {
        ok = ok && (fabs(output_0[i] - expected_output_0[i]) < 0.0001);
    }
    if (!ok) {
        any_failed = true;
        printf("output #%s mismatch: \n", info->output_names[0]);
        printf("actual {\n    ");
        for (int i = 0; i < out_size; ++i) {
            printf("%.4f,", output_0[i]);
        }
        printf("\n}\nexpected {\n    ");
        for (int i = 0; i < out_size; ++i) {
            printf("%.4f,", expected_output_0[i]);
        }
        printf("\n}\n");
    }
    return any_failed;
}
``` 
?

This way all the parsing would be delegated to TCL and the C compiler, and we would gain more granularity by being able to run one specific testcase. We do also have more detailed reports here. At the same time, the code generating such test programs is shorter by a factor of 4.

Also, what exactly is the purpose of `doc.tcl`?

**Comment by codeplea** [comment]
I'm mostly opposed to this. I don't think having a separate executable for each test is a good idea. I would also like to reduce the TCL dependency in the future, not expand on it.

Smoke is useful to see that all the tests are running quickly, and that everything is covered.

If you would like more detailed reports from smoke, feel free to add that feature to smoke. It would also be very easy to add an optional command-line argument to smoke specifying the indicator to run.

`doc.tcl` is used to generate documentation that is at https://tulipindicators.org

**Comment by rdbuf** [comment]
OK, got it, I'll try to improve smoke, then.

Could you please elaborate on how `doc.tcl` is related to `untest.txt`? Also, why don't we `count` test cases from it in smoke ([`0` here](https://github.com/TulipCharts/tulipindicators/blob/master/smoke.c#L214))?

**Comment by codeplea** [comment]
`untest.txt` is generated by `doc.tcl`. `untest.txt` just records the current output of each indicator. If `untest.txt` fails, the that indicators has changed since the last time `doc.tcl` was run. So it's a double-check to make sure indicator's aren't changing. i.e. regression testing

Smoke lists indicators which lack a unit-test. It doesn't count `untest.txt` for this, since `untest.txt` only tests for regressions/changes in an indicator, and doesn't imply that an indicator is in anyway correct.
