### ISSUE TITLE
compiliing with vc2010 so many erros

### ISSUE THREAD

**Issue by whidbey** [TulipCharts/tulipindicators#6]
do you have a .mak file?

**Comment by codeplea** [comment]
No.

You should be able to compile the library by adding `indicators_index.c` and all the `.c` files in the `indicators` and `utils` folders into a project.

**Comment by whidbey** [comment]
ok, I do it by cmake and change sqrt(period) to sqrt(double(period)) ,and works perfect on vs2010 now.
thanks
