### ISSUE TITLE
Stoch output stoch_k wrongly named sotchK

### ISSUE THREAD

**Issue by shimanotaka** [TulipCharts/tulipindicators#8]
Example output when using the indicator:
{ sotchK: 90.15000000749987, stochD: 62.46917123220644 }

**Comment by codeplea** [comment]
What bindings are you using? This is the repo for the C library, and [I don't think the problem is here](https://github.com/TulipCharts/tulipindicators/blob/cea7ea23af0145c92f2b40f84f9c5aa30bc6df97/indicators_index.c#L121).

**Comment by shimanotaka** [comment]
My bad! The typo was in a project (Gekko) implementing Tulip indicators. I should have checked closer but I'm pretty new at this. Sorry!
