### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by jayMcBee** [TulipCharts/tulipindicators#97]
I am aware of the possibility to e.g. sponsor new indicators, which sounds like a great way for major apps or institutions using Tulip Indicators to sponsor development.

However, I wonder if for individual developers or other, funded OSS projects could chip in via e.g. (potentially) small monthly pledges through Patreon or similar means?

In my experience this works well for a number of OSS frameworks - or even books and blogs - that provide significant value to many people :-)

**Comment by jayMcBee** [comment]
Donating cryptocurrency also comes to mind (as used by Wikipedia, WikiLeaks, ..)

**Comment by codeplea** [comment]
Good idea. I opened a Patreon page here: https://www.patreon.com/tulipcharts

Any suggestions on an easy to use crypto donation processor?

**Comment by bluelu** [comment]
Maybe you can add it more prominent like esphome does? https://github.com/esphome/esphome
![image](https://user-images.githubusercontent.com/339893/88559825-a21aea00-d02d-11ea-880a-b5ab3e4d2a6e.png)

**Comment by codeplea** [comment]
Great idea! Done.
